package com.redhat.demo.qlb.loan_application.rules;

import com.redhat.demo.utils.RuleConfig;

rule "config group"
when
    RuleConfig($ruleGroup : ruleGroup != null)
then
    System.out.println("config group: "+$ruleGroup);
    kcontext.getKnowledgeRuntime().getAgenda().getAgendaGroup($ruleGroup).setFocus();
end

// start a rule flow (aka process)
rule "start process"
salience -100
enabled false
when
    RuleConfig($startProcess : startProcess != null)
then
    System.out.println("start proc: "+$startProcess);
    kcontext.getKnowledgeRuntime().startProcess($startProcess);
end

rule "test"
enabled false
when
    $o : Object()
then
    System.out.println("wm: "+$o);
end