package com.redhat.demo.qlb.loan_application.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Applicant implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label("Credit Score")
	private int creditScore;

	@org.kie.api.definition.type.Label("Age")
	private int age;

	@org.kie.api.definition.type.Label("Eligible")
	private java.lang.Boolean eligible;

	@org.kie.api.definition.type.Label("Yearly Income")
	private int yearlyIncome;

	@org.kie.api.definition.type.Label(value = "Monthly Income")
	private java.lang.Double monthlyIncome;

	public Applicant() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public int getCreditScore() {
		return this.creditScore;
	}

	public void setCreditScore(int creditScore) {
		this.creditScore = creditScore;
	}

	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	public java.lang.Boolean getEligible() {
		return this.eligible;
	}

	public void setEligible(java.lang.Boolean eligible) {
		this.eligible = eligible;
	}

	public int getYearlyIncome() {
		return this.yearlyIncome;
	}

	public void setYearlyIncome(int yearlyIncome) {
		this.yearlyIncome = yearlyIncome;
	}

	@Override
	public String toString() {
		return "Applicant{" + "name='" + name + '\'' + ", age=" + age
				+ ", yearlyIncome=" + yearlyIncome + ", creditScore="
				+ creditScore + ", eligible=" + eligible + '}';
	}

	public java.lang.Double getMonthlyIncome() {
		return this.monthlyIncome;
	}

	public void setMonthlyIncome(java.lang.Double monthlyIncome) {
		this.monthlyIncome = monthlyIncome;
	}

	public Applicant(java.lang.String name, int creditScore, int age,
			java.lang.Boolean eligible, int yearlyIncome,
			java.lang.Double monthlyIncome) {
		this.name = name;
		this.creditScore = creditScore;
		this.age = age;
		this.eligible = eligible;
		this.yearlyIncome = yearlyIncome;
		this.monthlyIncome = monthlyIncome;
	}
}